turno zombies
javi-profe/Instrucciones-Zombicide pull request #6
Opened 2024-09-17 16:00 UTC by GuillermoFdzp

2024-09-17 16:00 UTC, GuillermoFdzp commented
turno de zombies explicacion

2024-09-17 20:25 UTC, javi-profe approved these changes

2024-09-17 20:33 UTC, javi-profe requested changes
Debes cambiar el nombre a las imágenes, ya hay una imagen.png

2024-09-20 11:37 UTC, GuillermoFdzp commented
cambio de nombre imagen

2024-09-20 11:40 UTC, merged